/******************************************************************************
*      (Exercise 5) Warfarin New Users 65 or Older at Index With Prior AFIB
******************************************************************************/             

WITH CTE_DRUG_INDEX AS (
       SELECT de.PERSON_ID, MIN(de.DRUG_EXPOSURE_START_DATE) AS INDEX_DATE
       FROM DRUG_EXPOSURE de
       WHERE de.DRUG_CONCEPT_ID IN (
             SELECT DESCENDANT_CONCEPT_ID FROM CONCEPT_ANCESTOR WHERE ANCESTOR_CONCEPT_ID = 1310149 /*warfarin*/
       )
       GROUP BY de.PERSON_ID
), 
CTE_DRUG_GR65 AS (
       SELECT i.PERSON_ID, i.INDEX_DATE, op.OBSERVATION_PERIOD_START_DATE, op.OBSERVATION_PERIOD_END_DATE,
             (i.INDEX_DATE-op.OBSERVATION_PERIOD_START_DATE) AS DAYS_BEFORE_INDEX, 
             EXTRACT(YEAR FROM i.INDEX_DATE)-p.YEAR_OF_BIRTH AS AGE_AT_INDEX
       FROM CTE_DRUG_INDEX i
             JOIN OBSERVATION_PERIOD op
                    ON op.PERSON_ID = i.PERSON_ID
                    AND i.INDEX_DATE BETWEEN op.OBSERVATION_PERIOD_START_DATE AND op.OBSERVATION_PERIOD_END_DATE
             JOIN PERSON p
                    ON p.PERSON_ID = i.PERSON_ID
       WHERE (i.INDEX_DATE-op.OBSERVATION_PERIOD_START_DATE) >= 180
       AND EXTRACT(YEAR FROM i.INDEX_DATE)-p.YEAR_OF_BIRTH >= 65
)
SELECT d.*,  MAX(d.INDEX_DATE-co.CONDITION_START_DATE) AS DAYS_OF_CLOSEST_AFIB_PRIOR_TO_INDEX
FROM CTE_DRUG_GR65 d
JOIN CONDITION_OCCURRENCE co
             ON co.PERSON_ID = d.PERSON_ID
             AND co.CONDITION_START_DATE BETWEEN d.OBSERVATION_PERIOD_START_DATE AND d.OBSERVATION_PERIOD_END_DATE
WHERE co.CONDITION_CONCEPT_ID IN (
             SELECT DESCENDANT_CONCEPT_ID FROM CONCEPT_ANCESTOR WHERE ANCESTOR_CONCEPT_ID =      313217 /*Atrial fibrillation*/           
)
AND co.CONDITION_START_DATE < d.INDEX_DATE
GROUP BY d.PERSON_ID, d.INDEX_DATE, d.OBSERVATION_PERIOD_START_DATE, d.OBSERVATION_PERIOD_END_DATE, d.DAYS_BEFORE_INDEX, d.AGE_AT_INDEX
ORDER BY d.PERSON_ID;
       
/******************************************************************************
*      (Exercise 6) clopidogrel New Users 65 or Older at Index With Prior AFIB
******************************************************************************/             
WITH CTE_DRUG_INDEX AS (
       SELECT de.PERSON_ID, MIN(de.DRUG_EXPOSURE_START_DATE) AS INDEX_DATE
       FROM DRUG_EXPOSURE de
       WHERE de.DRUG_CONCEPT_ID IN (
             SELECT DESCENDANT_CONCEPT_ID FROM CONCEPT_ANCESTOR WHERE ANCESTOR_CONCEPT_ID = 1322184 /*clopidogrel*/
       )
       GROUP BY de.PERSON_ID
), 
CTE_DRUG_GR65 AS (
       SELECT i.PERSON_ID, i.INDEX_DATE, op.OBSERVATION_PERIOD_START_DATE, op.OBSERVATION_PERIOD_END_DATE,
             (i.INDEX_DATE-op.OBSERVATION_PERIOD_START_DATE) AS DAYS_BEFORE_INDEX, 
             EXTRACT(YEAR FROM i.INDEX_DATE)-p.YEAR_OF_BIRTH AS AGE_AT_INDEX
       FROM CTE_DRUG_INDEX i
             JOIN OBSERVATION_PERIOD op
                    ON op.PERSON_ID = i.PERSON_ID
                    AND i.INDEX_DATE BETWEEN op.OBSERVATION_PERIOD_START_DATE AND op.OBSERVATION_PERIOD_END_DATE
             JOIN PERSON p
                    ON p.PERSON_ID = i.PERSON_ID
       WHERE (i.INDEX_DATE-op.OBSERVATION_PERIOD_START_DATE) >= 180
       AND EXTRACT(YEAR FROM i.INDEX_DATE)-p.YEAR_OF_BIRTH >= 65
)
SELECT d.*,  MAX(d.INDEX_DATE-co.CONDITION_START_DATE) AS DAYS_OF_CLOSEST_AFIB_PRIOR_TO_INDEX
FROM CTE_DRUG_GR65 d
JOIN CONDITION_OCCURRENCE co
             ON co.PERSON_ID = d.PERSON_ID
             AND co.CONDITION_START_DATE BETWEEN d.OBSERVATION_PERIOD_START_DATE AND d.OBSERVATION_PERIOD_END_DATE
WHERE co.CONDITION_CONCEPT_ID IN (
             SELECT DESCENDANT_CONCEPT_ID FROM CONCEPT_ANCESTOR WHERE ANCESTOR_CONCEPT_ID =      313217 /*Atrial fibrillation*/           
)
AND co.CONDITION_START_DATE < d.INDEX_DATE
GROUP BY d.PERSON_ID, d.INDEX_DATE, d.OBSERVATION_PERIOD_START_DATE, d.OBSERVATION_PERIOD_END_DATE, d.DAYS_BEFORE_INDEX, d.AGE_AT_INDEX
ORDER BY d.PERSON_ID;
































WITH CTE_DRUG_INDEX AS (
       SELECT de.PERSON_ID, MIN(de.DRUG_EXPOSURE_START_DATE) AS INDEX_DATE
       FROM DRUG_EXPOSURE de
       WHERE de.DRUG_CONCEPT_ID IN (
             SELECT DESCENDANT_CONCEPT_ID FROM CONCEPT_ANCESTOR WHERE ANCESTOR_CONCEPT_ID =      1322184 /*clopidogrel*/
       )
       GROUP BY de.PERSON_ID
), 
CTE_DRUG_GR65 AS (
       SELECT i.PERSON_ID, i.INDEX_DATE, op.OBSERVATION_PERIOD_START_DATE, op.OBSERVATION_PERIOD_END_DATE,
             DATEDIFF(DAY,op.OBSERVATION_PERIOD_START_DATE,i.INDEX_DATE) AS DAYS_BEFORE_INDEX, 
             (YEAR(i.INDEX_DATE)-p.YEAR_OF_BIRTH) AS AGE_AT_INDEX
       FROM CTE_DRUG_INDEX i
             JOIN OBSERVATION_PERIOD op
                    ON op.PERSON_ID = i.PERSON_ID
                    AND i.INDEX_DATE BETWEEN op.OBSERVATION_PERIOD_START_DATE AND op.OBSERVATION_PERIOD_END_DATE
             JOIN PERSON p
                    ON p.PERSON_ID = i.PERSON_ID
       WHERE DATEDIFF(DAY,op.OBSERVATION_PERIOD_START_DATE,i.INDEX_DATE) >= 180
       AND  (YEAR(i.INDEX_DATE)-p.YEAR_OF_BIRTH )>= 65
)
SELECT d.*, MIN(DATEDIFF(DAY,co.CONDITION_START_DATE,d.INDEX_DATE)) AS DAYS_OF_CLOSEST_AFIB_PRIOR_TO_INDEX
FROM CTE_DRUG_GR65 d
JOIN CONDITION_OCCURRENCE co
             ON co.PERSON_ID = d.PERSON_ID
             AND co.CONDITION_START_DATE BETWEEN d.OBSERVATION_PERIOD_START_DATE AND d.OBSERVATION_PERIOD_END_DATE
WHERE co.CONDITION_CONCEPT_ID IN (
             SELECT DESCENDANT_CONCEPT_ID FROM CONCEPT_ANCESTOR WHERE ANCESTOR_CONCEPT_ID =      313217 /*Atrial fibrillation*/           
)
AND co.CONDITION_START_DATE < d.INDEX_DATE
GROUP BY d.PERSON_ID, d.INDEX_DATE, d.OBSERVATION_PERIOD_START_DATE, d.OBSERVATION_PERIOD_END_DATE, d.DAYS_BEFORE_INDEX, d.AGE_AT_INDEX
ORDER BY d.PERSON_ID;